### ISSUE TITLE
Support for VSTS

### ISSUE THREAD

**Issue by jessehouwing** [reduckted/GitWebLinksVS2019#1]
Visual Studio Team Services offers a nice Web based view of code, changes, diffs etc. And since it always lives under the ...visualstudio.com domain, it should be relatively easy to detect the correct URL format.

**Comment by reduckted** [comment]
I've added this in v1.1, which is now live on the Visual Studio Marketplace. Thanks for the suggestion! 😄

**Comment by jessehouwing** [comment]
Woot
