### ISSUE TITLE
VS2017: not seeing any GitWebLinks behavior

### ISSUE THREAD

**Issue by lancehilliard** [reduckted/GitWebLinksVS2019#4]
Does this extension support VS2017 Professional? I have the extension installed, and my Git repository has a single remote which is the origin, but I see no extension behavior at all (except the Tools > Options > Git Web Links, which I do see).

**Comment by reduckted** [comment]
What's the remote URL of the repository? You can just post the host portion or obfuscate it if you don't want to post the whole thing - for example is it "https://github.com" or "git@github.com", or something else?

It could be that the extension isn't matching the remote URL to a known host. If I get a chance, I might add some logging to the next release to help debug problems like this.

**Comment by lancehilliard** [comment]
`https://company.visualstudio.com/DefaultCollection/_git/Project%20Name`

![Origin Dialog][dialog]

[dialog]: https://i.imgur.com/xOYBP8w.png "Origin Dialog"

**Comment by reduckted** [comment]
Ah, looks like the `/DefaultCollection/` part of the URL is causing it not to match. I wasn't aware that the URL could look like that. I'll try and get a fix out in the next few days.

**Comment by reduckted** [comment]
I've just published v1.1.2 which fixes this.

Thanks for reporting the problem. 😄
