### ISSUE TITLE
Doesn't work in VS2019

### ISSUE THREAD

**Issue by coosmiin** [reduckted/GitWebLinksVS2019#5]
Doesn't seem to work with VS2019 with VSTS.
![2019_04_17_11_55_50_Greenshot](https://user-images.githubusercontent.com/3222985/56274780-12874b80-6108-11e9-97be-c5a555f06fe6.png)

**Comment by reduckted** [comment]
Thanks for reporting this. 😄 

This extension used to support Visual Studio Team Services, but it seems that stopped working when Microsoft changed it to Azure DevOps. I've just published v1.3 with support for Azure DevOps. Can you give that a try and see if it works?

**Comment by coosmiin** [comment]
It works. Thanks.
