### ISSUE TITLE
Azure DevOps: link doesn't include the lineStartColumn or lineEndColumn

### ISSUE THREAD

**Issue by SharbelWired** [reduckted/GitWebLinksVS2019#6]
Hi there, thank-you for the extension.  I am experiencing an issue with Azure Devops links.  When I highlight a code block and get the link to it, the resulting link when visited, does not scroll down to the code block that I highlighted in VS.

In playing around, I noticed that the lineStartColumn and lineEndColumn querystring items were not appended to the constructed link from the extension.  When I add these to the link, it highlights the code block and scrolls down in AzureDevops as expected.

Any chance you can fix this?

**Comment by SharbelWired** [comment]
I actually pulled the source and enabled this functionality.  I can push the changes if you want, let me know.

**Comment by reduckted** [comment]
Closed by #7. Thanks!
